public class calculator 
{
    public static void addiction()
    {
        integer number1=12,number2=14 ,sum;
        sum=number1+number2;
        System.debug('addiction is ..'+sum);
    }
    
    
    public static void substraction()
    {
        
        integer number1=12,number2=14 ,sub;
        sub=number1-number2;
        System.debug('substraction is ..'+sub);
    }
    public static void multplication(integer num1,integer num2)
    {
        
        integer multi;
        multi=num1*num2;
        System.debug('multiplication'+multi);
        
    }
    public  void division(integer num1,integer num2)
    {   
        
        integer div;
        div=num1/num2;
        System.debug('multiplication'+div);
        
        
    }
}